id: PCE949524
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Lodrö Rinchen
  language: bo
  description: 'Texts by Khenchen Ngawang Lodrö Rinchen (mkhan chen ngag dbang blo
    gros rin chen, 1892–1952):'
  volume:
    fee6a7282f89435694e39444a4cb6e2b:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Long Life Prayers
created_at: '2022-03-01T00:21:03.089297'
last_modified_at: '2022-03-01T00:21:03.089301'
statistics:
  total_words: 42
  total_non_words: 8
quality:
  non_words_ratio: 0.19
